### ISSUE TITLE
Kidney Shotted mobs vanish and teleport a distance away.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#346]
Roll rogue
damage mob to just before flee
kidney shot
damage to flee %
watch the teleport.

**Comment by Progressive335** [comment]
i tried and tested this before, never happened in PTR.

**Comment by Zooke** [comment]
Must just be my client, I'll redownload.

**Comment by Zooke** [comment]
0.12
https://youtu.be/ZN2X8rg9qSo
0.45
https://youtu.be/wyCyu_UCfdk
I found some time to test this, even had to install the xbox recording app to do so, hate all that spyware stuff on my pc but did it just for you.
Seems replicating it wasn't as difficult as it sounded. 2 in 2 mins.

**Comment by LezChap** [comment]
I swear I've experienced it since the fix was pushed last week, but I wasn't taking notes.  When I took time out of my playing to try to help SilveR reproduce it, I wasn't able to...and said I'd continue to try while playing.

The second video is most interesting, and happens around 0:45 like you said.  You get him down to low HP, kidney shot him, he flees/teleports to the next mob...but then snaps back a few yards from where you were fighting him as what appears to be the Deadly Poison tick kills him mid-flee?  Definitely appears to be some sort of sync/desync/latency issue from that video.  What's your latency typically?

**Comment by flumby** [comment]
Issue confirmed.  I have seen it for my self, just as the npc is about to die he teleports back and glides across the floor forward again.

**Comment by LezChap** [comment]
I don't disagree it's happening...I'm still having problems replicating it right now.  I see the "flee" text from the mob, but I can't get my timing right to trigger the NPC teleport...testing on my rogue with both Kidney Shots and Gouges.  I hope Zooke is available for troubleshooting with SilveR when he gets back if I can't get the timing right.

**Comment by silverech0** [comment]
ahh i see, so they teleport BEFORE triggering the "run away in fear"

**Comment by silverech0** [comment]
I got it what happened! :) hopefully fixed !
