### ISSUE TITLE
Enchant Cloak - Greater Nature Resistance Bugged

### ISSUE THREAD

**Issue by Lampolo** [Progressive335/Progressive335#530]
Enchant Cloak - Greater Nature Resistance. it shows that it only requires Living Essence x4. Classic wow database shows that it requires Living Essence x4, Nexus Crystal x2, Large Brilliant Shard x8. also, even with all the materials on hand (all materials listed above), when you try to use the enchant it says, "Missing reagent: UNKNOWN".

**Comment by Progressive335** [comment]
the reason you saw "it requires living essence x4" was because you already had the other mats in your bag. also, you see "Missing reagent: UKNOWN" when you try to do it from the enchant tab because in WOTLK those recipes require TBC mats and that's the reason the Enchantweaver NPC was created, to "workaround" the issue because i was unable to edit the enchant tab with the classic materials.
tried now, while i have no mats in my bag
the error is:
![image](https://user-images.githubusercontent.com/44980177/73123093-d977e380-3f83-11ea-8482-296945a172bc.png)
