### ISSUE TITLE
[Gruuls/Magtheridon]

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#882]
- [x] Groon-priest wrong immunities

- [x] Doesn't call a heal at 50%

- [x] Brutes should be charging more often

- [x] Recheck Mag trash spells again

- [x] "Applies Mind Exhaustion to the player, preventing him from clicking it again for another 1 1/2 minutes. Magtheridon takes 200% damage while all 5 cubes are active." Change this spell to 90 seconds.

- [x] Dark mending from channelers doing low damage.

- [x] Fire from patches doing low damage.

**Comment by Zooke** [comment]
- [ ] https://www.wowhead.com/npc=18832/krosh-firehand
Hardly ever casts Blast wave 33061 even if i stand right next to him.
He should probably cast this after every fireball as it is the mechanic to force players to be 15 yards away.

**Comment by Zooke** [comment]
https://www.wowhead.com/npc=18835/kiggler-the-crazed
- [ ] He is not casting Lightning Bolt 36152 which should be his main attack as he is intended to be ranged tanked. (The way I understand this mob is that he will melee his highest aggro target if they are in melee range. If his highest aggro target is beyond 8 yards he will use his lightning bolt instead of melee)
- [ ] His Arcane Explosion 33237 is not lowering threat as it should (50% reduction ?)

His polymorph should be able to hit anyone in range regardless of threat (Not tested)

**Comment by Zooke** [comment]
https://www.wowhead.com/npc=18834/olm-the-summoner
- [ ] Uses death coil with the know bugged effect of being a buff instead of a debuff.
- [ ] Uses https://wotlk.evowow.com/?spell=33129 which according to the wiki is supposed to stack but he isn't using it often enough to stack. (At 1 point this spell is listed at 900 damage which could be the pre-nerf amount).

**Comment by Zooke** [comment]
https://www.wowhead.com/npc=18836/blindeye-the-seer
All the write ups talk of a 10s Prayer of Mending spell that healed him to full.
"a very powerful 10-second cast [Prayer of Mending] which heals him to full. Before he casts Prayer of Mending he will always [Power Word: Shield] himself first and can't be interrupted when the shield is up"
This spell is not in the 2.4.3 script so I have no idea when it was removed
It is an odd name for the spell because Prayer of Mending is the jumping heal ability, which makes me wonder if it is the correct name.
Either way, I think this would be a great addition to the encounter if we can find a suitable spell. Have him cast it at maybe 30%.

**Comment by Progressive335** [comment]
> https://www.wowhead.com/npc=18836/blindeye-the-seer
> All the write ups talk of a 10s Prayer of Mending spell that healed him to full.
> "a very powerful 10-second cast [Prayer of Mending] which heals him to full. Before he casts Prayer of Mending he will always [Power Word: Shield] himself first and can't be interrupted when the shield is up"
> This spell is not in the 2.4.3 script so I have no idea when it was removed
> It is an odd name for the spell because Prayer of Mending is the jumping heal ability, which makes me wonder if it is the correct name.
> Either way, I think this would be a great addition to the encounter if we can find a suitable spell. Have him cast it at maybe 70% and 30%.

![image](https://user-images.githubusercontent.com/44980177/83705703-94d51680-a60d-11ea-8872-21f2ee68f814.png)
he was already casting.
