### ISSUE TITLE
[BWL] Chromaggus

### ISSUE THREAD

**Issue by silverech0** [Progressive335/Progressive335#97]
Fight is not correct, should be fixed.

**Comment by Shrizz** [comment]
My last server had issues with this, in particular, the Bronze debuff was effectively chain-stunning. That is not the correct behaviour. There should be a fair degree of randomness with it, similar to the Remote Toy stun debuff from the engineer boss in the KT fight in Tempest Keep. Sure, it is possible to get stunned a second or so after it expires, but it should be unlikely. Generally you have a few seconds of free time before it reapplies. I would guess a random 1-6 second interval, based on my memories of farming TK for the phoenix mount on a weekly basis with many characters.
While we're on that issue, since the raid will have fewer people in it (25 vs 40), you might consider adjusting the frequency he can apply it, or increase the Hourglass Sand drop rate.

**Comment by Progressive335** [comment]
this issue wont be fixed since the actual fight is more challenging than the "fixed" version. boss is doable, just a bit harder.
